#!/usr/bin/env python3
import torch
from PIL import Image
from diffusers import AutoencoderKL, ControlNetModel, EulerDiscreteScheduler
from diffusers import StableDiffusionControlNetPipeline
import argparse

CACHE_DIR = "./hf-cache"

vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse")
controlnet = ControlNetModel.from_pretrained(
    "AlYa1141/another-qr-code-generator"
)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    vae=vae
).to("cuda")
pipe.save_pretrained(CACHE_DIR, safe_serialization=True)